### ISSUE TITLE
Induction meeting for India

### ISSUE THREAD

**Issue by leouieda** [compgeolab/manual#2]
## Before your meeting

- [x] Join the Slack chat room (click the link in the invitation and create an account). Setup Slack on your computer/tablet/phone or use the website version: [compgeolab.slack.com][slack]
- [x] Create an account on [GitHub](https://github.com/). Make it something professional (this will be associated with
   your future publications from the lab!)
- [x] Leave a comment here with your GitHub username

## During the meeting

Go over key information about:

- [x] The [lab manual](https://github.com/compgeolab/manual), expectations, and practices
- [x] The [lab GitHub organization][gh] where all our research projects live
- [x] The [lab website][website] and how you can add yourself to it

## After your meeting

- [ ] Go over the lab manual again on your own (ask on Slack if you have any questions).
- [ ] Read the [Code of Conduct][coc] carefully.
- [ ] Study the [Software Carpentry][swc] lessons on Version Control with Git, Python, and the Unix Shell. They will be crucial for your project. Go over Git and the Unix Shell first.
- [x] Edit your page on the website (if you want). See the website [contributing guide][website-contrib] for instructions.
- [ ] Explore the GitHub organization to see what the group is working on.
- [ ] Go and start making something brilliant!

## Checklist for Leo

- [x] Send invitation to the group [Slack](https://slack.com/) chat room
- [x] Add to the [lab GitHub organization][gh].
- [x] Add to the [lab HackMD][hmd] for share note taking.

[coc]: https://github.com/compgeolab/manual/blob/main/CODE_OF_CONDUCT.md
[website-contrib]: https://github.com/compgeolab/website/blob/main/CONTRIBUTING.md
[website]: https://www.compgeolab.org
[swc]: https://software-carpentry.org/lessons/
[gh]: https://github.com/compgeolab/
[slack]: https://compgeolab.slack.com
[hmd]: https://hackmd.io/team/compgeolab?nav=overview

**Comment by indiauppal** [comment]
GitHub username: indiauppal

**Comment by leouieda** [comment]
@indiauppal thanks for posting your username! You should have received an invitation to this GitHub organization. We host all project work here, including final year dissertations, papers, data compilations, etc. After you accept the invitation, you should be able to see all the private repositories here: https://github.com/compgeolab

Examples:

* This is @santisoler's latest paper which was just published: https://github.com/compgeolab/eql-gradient-boosted
* This is @dangilbert1337's dissertation from last year that did a particularly good job of using the platform: https://github.com/compgeolab/eql-model-selection

We'll go over all of this in our meeting on Friday.

PS: You can use emoji 👯 and other fancy formatting anywhere on GitHub. See [this guide](https://guides.github.com/features/mastering-markdown/).

**Comment by leouieda** [comment]
Things to get you started:

* Read this review: https://doi.org/10.5194/tc-14-3843-2020
* Do the following [Software Carpentry](https://software-carpentry.org/lessons/) lessons (in this order):
   * The Unix Shell
   * Version control with git
   * Programming with Python
